# Generated by Django 6.0.1 on 2026-03-06 23:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presente', '0016_alter_activity_created_at_alter_activity_end_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Campus',
                'verbose_name_plural': 'Campi',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Gamificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Nome da gamificação ou conquista', max_length=150, verbose_name='Título')),
                ('pontos', models.PositiveIntegerField(default=0, help_text='Quantidade de pontos concedidos', verbose_name='Pontos')),
            ],
            options={
                'verbose_name': 'Gamificação',
                'verbose_name_plural': 'Gamificações',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='TipoGamificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('BDG', 'Badge'), ('TRF', 'Troféu'), ('MDL', 'Medalha')], max_length=3, verbose_name='Tipo')),
                ('icone', models.ImageField(blank=True, null=True, upload_to='gamificacao/icones/', verbose_name='Ícone')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Tipo de gamificação',
                'verbose_name_plural': 'Tipos de gamificação',
                'ordering': ['tipo'],
            },
        ),
        migrations.CreateModel(
            name='TrilhaGamificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Trilha de Entrada', max_length=100, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, help_text='Descrição da trilha', verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Trilha',
                'verbose_name_plural': 'Trilhas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('data_inicio', models.DateTimeField(verbose_name='Data de Início')),
                ('data_fim', models.DateTimeField(verbose_name='Data de Fim')),
                ('tipo', models.CharField(choices=[('EXP', 'EXPOTEC'), ('SEM', 'SEMADEC'), ('OUT', 'Outro')], max_length=3, verbose_name='Tipo')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('campus', models.ManyToManyField(related_name='eventos', to='presente.campus', verbose_name='Campus')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='presente.evento', verbose_name='Evento'),
        ),
        migrations.AddField(
            model_name='activity',
            name='gamificacao',
            field=models.ForeignKey(blank=True, help_text='Gamificação concedida ao registrar presença nesta atividade.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='presente.gamificacao', verbose_name='Gamificação associada'),
        ),
        migrations.AddField(
            model_name='gamificacao',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gamificacoes', to='presente.tipogamificacao', verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='tipogamificacao',
            name='trilha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos', to='presente.trilhagamificacao'),
        ),
        migrations.AddField(
            model_name='gamificacao',
            name='trilha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamificacoes', to='presente.trilhagamificacao', verbose_name='Trilha'),
        ),
        migrations.AddField(
            model_name='activity',
            name='trilha',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='presente.trilhagamificacao', verbose_name='Trilha'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UsuarioGamificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_concedida', models.DateTimeField(auto_now_add=True, verbose_name='Data concedida')),
                ('gamificacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='presente.gamificacao', verbose_name='Gamificação')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamificacoes_recebidas', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Gamificação do usuário',
                'verbose_name_plural': 'Gamificações dos usuários',
            },
        ),
        migrations.AddConstraint(
            model_name='tipogamificacao',
            constraint=models.UniqueConstraint(fields=('trilha', 'tipo'), name='unique_tipo_por_trilha'),
        ),
        migrations.AlterUniqueTogether(
            name='usuariogamificacao',
            unique_together={('user', 'gamificacao')},
        ),
    ]
