# Generated by Django 5.2.7 on 2026-03-28 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presente', '0017_campus_gamificacao_tipogamificacao_trilhagamificacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Informática, Jogos, EBM', max_length=100, unique=True, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Área',
                'verbose_name_plural': 'Áreas',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='area',
            field=models.ForeignKey(blank=True, help_text='Área temática desta atividade', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='presente.area', verbose_name='Área'),
        ),
        migrations.CreateModel(
            name='MarcosDiversidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areas_necessarias', models.PositiveIntegerField(help_text='Quantidade de áreas diferentes no mesmo dia para ganhar o bônus', verbose_name='Áreas necessárias')),
                ('descricao', models.TextField(blank=True, help_text='Ex: Participou de 3 áreas diferentes no mesmo dia', verbose_name='Descrição')),
                ('gamificacao_bonus', models.ForeignKey(help_text='Gamificação concedida ao atingir este marco', on_delete=django.db.models.deletion.CASCADE, related_name='marcos_diversidade', to='presente.gamificacao', verbose_name='Gamificação de bônus')),
            ],
            options={
                'verbose_name': 'Marco de Diversidade',
                'verbose_name_plural': 'Marcos de Diversidade',
                'ordering': ['areas_necessarias'],
            },
        ),
    ]