# Generated by Django 5.2.7 on 2026-03-28 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presente', '0017_campus_gamificacao_tipogamificacao_trilhagamificacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trilhagamificacao',
            name='gamificacao_bonus',
            field=models.ForeignKey(blank=True, help_text='Gamificação concedida ao completar a trilha. Os pontos do bônus são definidos nela.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trilhas_bonus', to='presente.gamificacao', verbose_name='Gamificação de bônus'),
        ),
        migrations.AddField(
            model_name='trilhagamificacao',
            name='minimo_atividades',
            field=models.PositiveIntegerField(default=1, help_text='Quantidade mínima de presenças na trilha para ganhar o bônus', verbose_name='Mínimo de atividades para completar'),
        ),
    ]
