# Generated by Django 5.2.7 on 2026-04-17 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presente', '0018_area_trilhagamificacao_gamificacao_bonus_and_more'),
        ('presente', '0018_trilhagamificacao_gamificacao_bonus_and_more'),
    ]

    operations = [
    ]
