# Generated by Django 6.0.1 on 2026-04-01 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presente', '0018_trilhagamificacao_gamificacao_bonus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariogamificacao',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
    ]
