# Generated by Django 5.2.7 on 2026-04-17 03:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presente', '0019_merge_20260417_0050'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='trilhagamificacao',
            name='gamificacao_bonus',
            field=models.ForeignKey(blank=True, help_text='Gamificação concedida ao completar a trilha.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trilhas_bonus', to='presente.gamificacao', verbose_name='Gamificação de bônus'),
        ),
        migrations.CreateModel(
            name='AttendanceRemovalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('removed_at', models.DateTimeField(auto_now_add=True, verbose_name='Removido em')),
                ('justificativa', models.TextField(help_text='Motivo da remoção da presença.', verbose_name='Justificativa')),
                ('checked_in_at_snapshot', models.DateTimeField(help_text='Data/hora original do check-in, preservada para histórico.', verbose_name='Registrado em (original)')),
                ('activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='removal_logs', to='presente.activity', verbose_name='Atividade')),
                ('attendance_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='removal_logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuário da presença')),
                ('removed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_removals', to=settings.AUTH_USER_MODEL, verbose_name='Removido por')),
            ],
            options={
                'verbose_name': 'Log de Remoção de Presença',
                'verbose_name_plural': 'Logs de Remoção de Presença',
                'ordering': ['-removed_at'],
            },
        ),
        migrations.CreateModel(
            name='PointHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CRD', 'Crédito'), ('DEB', 'Débito')], max_length=3, verbose_name='Tipo')),
                ('pontos', models.IntegerField(help_text='Positivo para crédito, negativo para débito.', verbose_name='Pontos')),
                ('motivo', models.TextField(blank=True, help_text='Descrição automática do motivo do movimento.', verbose_name='Motivo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('gamificacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_history', to='presente.gamificacao', verbose_name='Gamificação')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_history', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Histórico de Pontos',
                'verbose_name_plural': 'Histórico de Pontos',
                'ordering': ['-criado_em'],
            },
        ),
    ]
