# Generated by Django 6.0.1 on 2026-04-07 01:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presente', '0019_usuariogamificacao_ativo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontos', models.PositiveIntegerField(default=0, help_text='Quantidade de pontos concedidos', verbose_name='Pontos')),
                ('tipo', models.CharField(choices=[('CREDIT', 'CREDIT'), ('DEBIT', 'DEBIT')], max_length=6, verbose_name='Tipo')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data concedida')),
                ('gamificacao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_gamificacao', to='presente.gamificacao', verbose_name='Gamificação')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacao_user', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Movimentação do usuário',
                'verbose_name_plural': 'Movimentações do usuário',
            },
        ),
    ]
