# Generated by Django 6.0.1 on 2026-04-07 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presente', '0020_movimentacao'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usuariogamificacao',
            unique_together=set(),
        ),
    ]
