# Generated by Django 6.0.1 on 2026-04-16 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presente', '0021_alter_usuariogamificacao_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuariogamificacao',
            options={},
        ),
        migrations.RemoveField(
            model_name='usuariogamificacao',
            name='ativo',
        ),
    ]
