# Generated by Django 6.0.1 on 2026-04-16 11:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presente', '0022_alter_usuariogamificacao_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usuariogamificacao',
            unique_together={('user', 'gamificacao')},
        ),
    ]
