# Generated by Django 6.0.1 on 2026-04-18 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presente', '0023_alter_usuariogamificacao_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('pontos_minimos', models.PositiveIntegerField(default=0, help_text='Quantidade de pontos mínimos para estar nesse nível', unique=True, verbose_name='Pontos mínimos')),
            ],
            options={
                'verbose_name': 'Nível',
                'verbose_name_plural': 'Níveis',
                'ordering': ['pontos_minimos'],
            },
        ),
        migrations.CreateModel(
            name='PerfilGamificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_gamificado', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
    ]
