# Generated by Django 6.0.1 on 2026-04-18 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presente', '0024_nivel_perfilgamificado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfilgamificado',
            options={'verbose_name': 'Perfil Gamificado', 'verbose_name_plural': 'Perfis Gamificados'},
        ),
        migrations.AddField(
            model_name='perfilgamificado',
            name='nivel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nivel_perfil', to='presente.nivel', verbose_name='Nível'),
        ),
        migrations.AddField(
            model_name='perfilgamificado',
            name='titulo',
            field=models.CharField(blank=True, max_length=155, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='perfilgamificado',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_gamificado', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
