# Generated by Django 6.0.1 on 2026-04-24 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presente', '0025_alter_perfilgamificado_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilgamificado',
            name='titulo',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Titulo'),
        ),
    ]
