# Generated by Django 5.2.7 on 2026-05-09 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presente', '0020_alter_trilhagamificacao_gamificacao_bonus_and_more'),
        ('presente', '0026_alter_perfilgamificado_titulo'),
    ]

    operations = [
    ]
