# Generated by Django 5.2.7 on 2026-05-14 03:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presente', '0027_merge_20260509_1203'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointhistory',
            name='gamificacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='point_history', to='presente.gamificacao', verbose_name='Gamificação'),
        ),
        migrations.CreateModel(
            name='Recompensa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('pontos_necessarios', models.PositiveIntegerField(help_text='Quantidade de pontos para resgatar esta recompensa.', verbose_name='Pontos necessários')),
                ('quantidade_disponivel', models.PositiveIntegerField(help_text='Estoque disponível para resgate.', verbose_name='Quantidade disponível')),
                ('data_validade', models.DateField(blank=True, null=True, verbose_name='Data de validade')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('evento', models.ForeignKey(help_text='Evento ao qual esta recompensa pertence.', on_delete=django.db.models.deletion.CASCADE, related_name='recompensas', to='presente.evento', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'Recompensa',
                'verbose_name_plural': 'Recompensas',
                'ordering': ['pontos_necessarios'],
            },
        ),
        migrations.CreateModel(
            name='ResgateRecompensa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontos_gastos', models.PositiveIntegerField(help_text='Snapshot dos pontos no momento do resgate.', verbose_name='Pontos gastos')),
                ('resgatado_em', models.DateTimeField(auto_now_add=True, verbose_name='Resgatado em')),
                ('recompensa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resgates', to='presente.recompensa', verbose_name='Recompensa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resgates', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Resgate de Recompensa',
                'verbose_name_plural': 'Resgates de Recompensas',
                'ordering': ['-resgatado_em'],
            },
        ),
        migrations.DeleteModel(
            name='Movimentacao',
        ),
    ]
