# Generated by Django 5.2.7 on 2026-05-20 23:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presente', '0028_alter_pointhistory_gamificacao_recompensa_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resgaterecompensa',
            name='recompensa',
        ),
        migrations.RemoveField(
            model_name='resgaterecompensa',
            name='usuario',
        ),
        migrations.CreateModel(
            name='Brinde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('pontos_necessarios', models.PositiveIntegerField(help_text='Custo em pontos por unidade deste brinde.', verbose_name='Pontos necessários')),
                ('quantidade_disponivel', models.PositiveIntegerField(help_text='Estoque total disponível para troca.', verbose_name='Quantidade disponível')),
                ('data_validade', models.DateField(blank=True, null=True, verbose_name='Data de validade')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('evento', models.ForeignKey(help_text='Evento ao qual este brinde pertence.', on_delete=django.db.models.deletion.CASCADE, related_name='brindes', to='presente.evento', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'Brinde',
                'verbose_name_plural': 'Brindes',
                'ordering': ['pontos_necessarios'],
            },
        ),
        migrations.CreateModel(
            name='Troca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontos_gastos', models.PositiveIntegerField(help_text='Total de pontos gastos nesta troca (soma de todos os itens).', verbose_name='Pontos gastos')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data da troca')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trocas', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Troca',
                'verbose_name_plural': 'Trocas',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='ItemRecompensa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1, help_text='Quantidade de unidades deste brinde nesta troca.', verbose_name='Quantidade')),
                ('pontos_unitarios', models.PositiveIntegerField(help_text='Snapshot do custo por unidade no momento da troca.', verbose_name='Pontos unitários')),
                ('brinde', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens', to='presente.brinde', verbose_name='Brinde')),
                ('troca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='presente.troca', verbose_name='Troca')),
            ],
            options={
                'verbose_name': 'Item de Recompensa',
                'verbose_name_plural': 'Itens de Recompensa',
            },
        ),
        migrations.DeleteModel(
            name='Recompensa',
        ),
        migrations.DeleteModel(
            name='ResgateRecompensa',
        ),
    ]
