# Generated by Django 6.0.1 on 2026-08-31 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presente', '0029_remove_resgaterecompensa_recompensa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conquista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=155, verbose_name='Nome Conquista')),
                ('descricao', models.TextField(blank=True, help_text='Descrição da Conquista', verbose_name='Descrição')),
                ('icone', models.ImageField(blank=True, null=True, upload_to='gamificacao/icones/', verbose_name='Ícone')),
                ('pontos', models.PositiveIntegerField(default=0, help_text='Quantidade de pontos da conquista', verbose_name='Pontos')),
                ('status', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
        ),
    ]
