# Generated by Django 5.2.7 on 2026-09-09 00:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presente', '0029_remove_resgaterecompensa_recompensa_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Missao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('tipo', models.CharField(choices=[('FREQ', 'Frequência'), ('SEQ', 'Sequência de presenças'), ('DIV', 'Diversidade de áreas'), ('OUT', 'Outro')], default='OUT', max_length=4, verbose_name='Tipo')),
                ('meta', models.PositiveIntegerField(default=1, help_text='Valor necessário para completar a missão (ex: nº de presenças)', verbose_name='Meta')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('data_inicio', models.DateField(blank=True, null=True, verbose_name='Início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Fim')),
                ('criada_em', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('gamificacao', models.ForeignKey(help_text='Badge/troféu/medalha concedido ao completar a missão.', on_delete=django.db.models.deletion.PROTECT, related_name='missoes', to='presente.gamificacao', verbose_name='Gamificação concedida')),
            ],
            options={
                'verbose_name': 'Missão',
                'verbose_name_plural': 'Missões',
                'ordering': ['-criada_em'],
            },
        ),
        migrations.CreateModel(
            name='MissaoProgresso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progresso', models.PositiveIntegerField(default=0, verbose_name='Progresso')),
                ('concluida_em', models.DateTimeField(blank=True, null=True, verbose_name='Concluída em')),
                ('missao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresso_usuarios', to='presente.missao', verbose_name='Missão')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missoes_progresso', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Progresso de Missão',
                'verbose_name_plural': 'Progressos de Missão',
                'constraints': [models.UniqueConstraint(fields=('user', 'missao'), name='unique_missao_por_usuario')],
            },
        ),
    ]
