# Generated by Django 6.0.1 on 2026-08-31 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presente', '0030_conquista'),
    ]

    operations = [
        migrations.AddField(
            model_name='conquista',
            name='tipo_regra',
            field=models.CharField(choices=[('Número de Presenças', 'Numero De Presencas'), ('Número de Áreas Diferentes', 'Numero Areas Diferentes'), ('Número de Atividades', 'Numero Atividades'), ('Primeira Presença', 'Primeira Presenca')], default='', max_length=155, verbose_name='Tipo da Regra'),
        ),
    ]
