# Generated by Django 6.0.1 on 2026-09-09 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presente', '0031_conquista_tipo_regra'),
    ]

    operations = [
        migrations.AddField(
            model_name='conquista',
            name='valor_necessario',
            field=models.PositiveIntegerField(default=1, help_text='Valor necessário para alcançar a conquista', verbose_name='Valor necessário'),
        ),
        migrations.AlterField(
            model_name='conquista',
            name='tipo_regra',
            field=models.CharField(choices=[('NUMERO_PRESENCAS', 'Número de Presenças'), ('NUMERO_AREAS_DIFERENTES', 'Número de Áreas Diferentes'), ('NUMERO_ATIVIDADES', 'Número de Atividades'), ('PRIMEIRA_PRESENCA', 'Primeira Presença')], default='PRIMEIRA_PRESENCA', max_length=155, verbose_name='Tipo da Regra'),
        ),
    ]
