# Generated by Django 6.0.1 on 2026-09-09 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presente', '0032_conquista_valor_necessario_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConquistaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_desbloqueio', models.DateField(auto_now_add=True, verbose_name='Data de desbloqueio da conquista')),
                ('conquista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presente.conquista', verbose_name='Conquista do Usuário')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presente.evento', verbose_name='Evento da conquista')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'conquista'), name='unique_usuario_conquista')],
            },
        ),
    ]
