# Generated by Django 6.0.1 on 2026-09-10 00:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presente', '0033_conquistausuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='conquistausuario',
            name='unique_usuario_conquista',
        ),
        migrations.AlterField(
            model_name='activity',
            name='evento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='presente.evento', verbose_name='Evento'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='conquistausuario',
            constraint=models.UniqueConstraint(fields=('user', 'conquista', 'evento'), name='unique_usuario_conquista_evento'),
        ),
    ]
