# Generated by Django 5.2.7 on 2026-09-26 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presente', '0034_remove_conquistausuario_unique_usuario_conquista_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointhistory',
            name='evento',
            field=models.ForeignKey(blank=True, help_text='Evento ao qual este crédito/débito está vinculado, quando aplicável.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_history', to='presente.evento', verbose_name='Evento'),
        ),
    ]
