# Generated by Django 6.0.1 on 2026-09-26 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presente', '0036_backfill_pointhistory_evento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trilhagamificacao',
            name='evento',
            field=models.ForeignKey(blank=True, help_text='Trilhas de um evento precisam ser escolhidas pelo aluno. Sem evento, a trilha vale automaticamente para todos.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trilhas', to='presente.evento', verbose_name='Evento'),
        ),
        migrations.CreateModel(
            name='InscricaoTrilha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Inscrito em')),
                ('trilha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='presente.trilhagamificacao', verbose_name='Trilha')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes_trilha', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Inscrição em trilha',
                'verbose_name_plural': 'Inscrições em trilhas',
                'constraints': [models.UniqueConstraint(fields=('user', 'trilha'), name='unique_inscricao_trilha')],
            },
        ),
    ]
