# Generated by Django 6.0.1 on 2026-09-26 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presente', '0037_trilha_evento_inscricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='descricao',
            field=models.TextField(blank=True, help_text='O que o participante vai ver ou fazer nesta atividade.', verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='activity',
            name='local',
            field=models.CharField(blank=True, help_text="Onde acontece (ex: 'Bloco B — Laboratório 3').", max_length=200, verbose_name='Local'),
        ),
        migrations.AddField(
            model_name='activity',
            name='ministrante',
            field=models.CharField(blank=True, help_text='Quem conduz a atividade (palestrante, professor, equipe).', max_length=150, verbose_name='Ministrante'),
        ),
    ]
