# Generated by Django 6.0.1 on 2026-09-26 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presente', '0038_activity_local_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='trilha',
            field=models.ForeignKey(blank=True, help_text='Opcional. A presença conta para o bônus desta trilha.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='presente.trilhagamificacao', verbose_name='Trilha'),
        ),
        migrations.AlterField(
            model_name='gamificacao',
            name='tipo',
            field=models.ForeignKey(blank=True, help_text='Vazio para os pontos de presença criados automaticamente pela atividade.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gamificacoes', to='presente.tipogamificacao', verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='gamificacao',
            name='trilha',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gamificacoes', to='presente.trilhagamificacao', verbose_name='Trilha'),
        ),
    ]
