# Generated by Django 5.2.7 on 2026-10-06 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presente', '0030_missao_missaoprogresso'),
        ('presente', '0041_bau_trilha'),
    ]

    operations = [
    ]
